[tool.black]
line-length = 80
target-version = ['py311']
exclude = '/.*(__pycache__).*/'

[build-system]
requires = ["scikit_build_core", "nanobind"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
build.verbose = false
build-dir = "build/{wheel_tag}"

[[tool.scikit-build.overrides]]
if.failed = true
wheel.cmake = false

[tool.scikit-build.sdist]
exclude = ["*"]
include = [
    "bmsspy/*.py",
    "bmsspy/data_structures/*.py",
    "bmsspy/helpers/*.py",
    "bmsspy/cpp/*",
    "pyproject.toml",
    "CMakeLists.txt",
    "README.md",
    "LICENSE",
]

[project]
name = "bmsspy"
version = "2.2.2"
description = "A pure python and C++ bmssp solver"
authors = [
    {name="Connor Makowski", email="conmak@mit.edu"}
]
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: C++",
    'License :: OSI Approved :: MIT License',
    "Operating System :: OS Independent",
]
dependencies = []

[project.optional-dependencies]
dev = [
    "pamda==2.8.1",
    "scgraph==3.4.1",
    "pytest>=9.0.3",
    "autoflake>=2.3.1",
    "black>=25.1.0",
    "build>=1.2.2",
    "nox>=2026.4.10",
    "nox-uv>=0.8.0",
    "pdoc>=15.0.1",
    "twine>=6.1.0",
    "scikit-build-core>=1.0.3",
    "nanobind>=3.0.0",
]
bench = [
    "igraph==0.11.9",
    "networkx==3.6",
    "folium==0.20.0",
    "ipykernel==6.30.1",
    "matplotlib==3.10.6",
    "scipy==1.16.2",
]

[project.urls]
"Homepage" = "https://github.com/connor-makowski/bmsspy"
"Bug Tracker" = "https://github.com/connor-makowski/bmsspy/issues"
"Documentation" = "https://connor-makowski.github.io/bmsspy/bmsspy.html"

[tool.uv]
no-build-isolation-package = []

[tool.pytest.ini_options]
testpaths = ["test"]
python_files = ["*.py"]
pythonpath = ["."]
